/*******************************************************************************
 *
 * SonarQube MsCover Plugin
 * Copyright (C) 2015 SonarSource
 * dev@sonar.codehaus.org
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02
 *
 * Author: Peter Stevens, peter@famstevens.eu
 *******************************************************************************/
package com.stevpet.sonar.plugins.dotnet.utils.vstowrapper;

import java.io.File;
import java.util.List;

public interface VisualStudioProject {

    /**
     * get the name of the assembly generated by this project, without the extension
     * @return
     */
    String getAssemblyName();

    boolean isUnitTest();

    String getArtifactName();

    File getDirectory();

    boolean isTest();

    String outputType();
    
    List<File> getSourceFiles();
    
    String getLanguage();

    /**
     * set the name of the project as defined in the solution
     * @param projectName
     */
	void setProjectName(String projectName);

	/**
	 * get the name of the project as defined in the solution
	 * @return 
	 */
	String getProjectName();

	void setIsTest();

	File getArtifactFile();


}